// SPDX-License-Identifier: GPL-2.0

//! This module provides types for implementing block drivers that interface the
//! blk-mq subsystem.
//!
//! To implement a block device driver, a Rust module must do the following:
//!
//! - Implement [`Operations`] for a type `T`.
//! - Create a [`TagSet<T>`].
//! - Create and add a [`GenDisk<T>`] to the system by calling
//!   [`GenDisk::new`] passing in the `TagSet` reference.
//!
//! The types available in this module that have direct C counterparts are:
//!
//! - The [`TagSet`] type that abstracts the C type `struct tag_set`.
//! - The [`GenDisk`] type that abstracts the C type `struct gendisk`.
//! - The [`Request`] type that abstracts the C type `struct request`.
//!
//! Many of the C types that this module abstracts allow a driver to carry
//! private data, either embedded in the struct directly, or as a C `void*`. In
//! these abstractions, this data is typed. The types of the data is defined by
//! associated types in `Operations`, see [`Operations::RequestData`] for an
//! example.
//!
//! The kernel will interface with the block device driver by calling the method
//! implementations of the `Operations` trait.
//!
//! IO requests are passed to the driver as [`kernel::sync::aref::ARef<Request>`]
//! instances. The `Request` type is a wrapper around the C `struct request`.
//! The driver must mark end of processing by calling one of the
//! `Request::end`, methods. Failure to do so can lead to deadlock or timeout
//! errors. Please note that the C function `blk_mq_start_request` is implicitly
//! called when the request is queued with the driver.
//!
//! The `TagSet` is responsible for creating and maintaining a mapping between
//! `Request`s and integer ids as well as carrying a pointer to the vtable
//! generated by `Operations`. This mapping is useful for associating
//! completions from hardware with the correct `Request` instance. The `TagSet`
//! determines the maximum queue depth by setting the number of `Request`
//! instances available to the driver, and it determines the number of queues to
//! instantiate for the driver. If possible, a driver should allocate one queue
//! per core, to keep queue data local to a core.
//!
//! One `TagSet` instance can be shared between multiple `GenDisk` instances.
//! This can be useful when implementing drivers where one piece of hardware
//! with one set of IO resources are represented to the user as multiple disks.
//!
//! One significant difference between block device drivers implemented with
//! these Rust abstractions and drivers implemented in C, is that the Rust
//! drivers have to own a reference count on the `Request` type when the IO is
//! in flight. This is to ensure that the C `struct request` instances backing
//! the Rust `Request` instances are live while the Rust driver holds a
//! reference to the `Request`. In addition, the conversion of an integer tag to
//! a `Request` via the `TagSet` would not be sound without this bookkeeping.
//!
//! [`GenDisk`]: gen_disk::GenDisk
//! [`GenDisk<T>`]: gen_disk::GenDisk
//! [`GenDisk::new`]: gen_disk::GenDisk::new
//!
//! # Examples
//!
//! ```rust
//! use kernel::{
//!     alloc::{flags, NumaNode},
//!     block::{error::BlkResult, mq::{self, *}},
//!     new_mutex,
//!     prelude::*,
//!     sync::{aref::ARef, Arc, Mutex},
//!     types::{ForeignOwnable, OwnableRefCounted, Owned},
//! };
//!
//! struct MyBlkDevice;
//!
//! impl kernel::ModuleMetadata for MyBlkDevice {
//!     const NAME: &'static kernel::str::CStr = kernel::c_str!("myblk");
//!     // SAFETY: This example is not built as a module, so the module pointer is null.
//!     const THIS_MODULE: kernel::ThisModule =
//!         unsafe { kernel::ThisModule::from_ptr(core::ptr::null_mut()) };
//! }
//!
//! #[vtable]
//! impl Operations for MyBlkDevice {
//!     const MODULE: &'static kernel::ThisModule = kernel::module::this_module::<MyBlkDevice>();
//!
//!     type RequestData = ();
//!     type QueueData = ();
//!     type HwData = ();
//!     type TagSetData = ();
//!     type GenDiskData = ();
//!
//!     fn new_request_data(
//!     ) -> impl PinInit<()> {
//!         Ok(())
//!     }
//!
//!     fn queue_rq(
//!         _hw_data: (),
//!         _queue_data: (),
//!         rq: Owned<IdleRequest<Self>>,
//!         _is_last: bool,
//!     ) -> BlkResult {
//!         rq.start().end_ok();
//!         Ok(())
//!     }
//!
//!     fn commit_rqs(_hw_data: (), _queue_data: ()) {}
//!
//!     fn complete(rq: ARef<Request<Self>>) {
//!         OwnableRefCounted::try_from_shared(rq)
//!             .map_err(|_e| kernel::error::code::EIO)
//!             .expect("Fatal error - expected to be able to end request")
//!             .end_ok();
//!     }
//!
//!     fn init_hctx(
//!         _tagset_data: (),
//!         _hctx_idx: u32,
//!     ) -> Result<Self::HwData> {
//!         Ok(())
//!     }
//! }
//!
//! let tagset: Arc<TagSet<MyBlkDevice>> = Arc::pin_init(
//!     TagSet::new(
//!         1,
//!         (),
//!         256,
//!         1,
//!         NumaNode::NO_NODE,
//!         mq::tag_set::Flags::default(),
//!     ),
//!     flags::GFP_KERNEL,
//! )?;
//! let limits = LimitsBuilder::<MyBlkDevice>::new().build()?;
//! let disk = gen_disk::GenDisk::new(fmt!("myblk"), tagset, (), limits, (), 4096, 256)?;
//!
//! # Ok::<(), kernel::error::Error>(())
//! ```

/// DMA mapping iterator for block requests.
pub mod dma_map_iter;
/// Single-buffer DMA mappings detached from a block request borrow.
pub mod dma_map_single;
mod feature;
pub mod gen_disk;
mod operations;
mod request;
mod request_queue;
pub mod tag_set;

pub use feature::{
    Feature,
    Features, //
};
pub use operations::{
    IoCompletionBatch,
    Operations,
    RequestTimeoutStatus, //
};
pub use request::{
    Command,
    Flag as RequestFlag,
    Flags as RequestFlags,
    IdleRequest,
    Request, //
};
pub use request_queue::{
    BoundRequestQueue, //
    Limits,
    LimitsBuilder,
    RequestQueue,
};
pub use tag_set::{
    QueueType,
    TagSet, //
};
